"""
Writes docs/dynamic_fields_report.md: a snapshot of every tenant-specific
column that discover_unmapped_columns() has classified into
dynamic_field_registry so far.

IMPORTANT — this is NOT an ER diagram, and deliberately doesn't try to be
one. The actual table structure (docs/er_diagram.md) is fixed and doesn't
change per tenant — that's the whole point of the extra_attributes/
dynamic_field_registry design: tenant-specific columns extend what the
*reasoning* layer considers without ever altering the SQL schema. This
report just makes that per-tenant extension visible, since it isn't
represented anywhere in the static schema/ER diagram.

Run this after scripts/run_tenant_ingestion.py.

Usage:
    python scripts/generate_dynamic_fields_report.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import db

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "docs", "dynamic_fields_report.md")


def _distinct_tenants() -> list[str]:
    conn = db.get_connection()
    cur = conn.cursor()
    cur.execute("SELECT DISTINCT tenant_id FROM dynamic_field_registry ORDER BY tenant_id")
    tenants = [r[0] for r in cur.fetchall()]
    conn.close()
    return tenants


def _print_console_summary(tenants: list[str]) -> None:
    """Compact tenant x dataset_type x count table to stdout, so a quick
    sanity check (e.g. 'did usage_metrics discovery actually find anything
    for initech?') doesn't require an ad-hoc python -c query against db.py.
    Counts EXCLUDE ignored fields, since those are the ones that actually
    reach reasoning -- that's the number you care about when checking
    whether the fix worked, not the raw discovery count.
    """
    if not tenants:
        print("No dynamic fields discovered yet.")
        return

    # Known reasoning-side dataset types as of app/dynamic_context.py --
    # kept here only for the "wired in?" column below, since the DB itself
    # doesn't know which dataset types have a build_*_dynamic_field_context
    # consumer. Update this set if a new builder is added.
    WIRED_IN = {"customers", "support_tickets", "usage_metrics"}

    print()
    print(f"{'tenant':<12} {'dataset_type':<16} {'count':>6}  wired_into_reasoning?")
    print("-" * 60)
    for tenant_id in tenants:
        fields = db.get_dynamic_fields(tenant_id, exclude_ignored=True)
        by_dataset = {}
        for f in fields:
            by_dataset.setdefault(f["dataset_type"], []).append(f)
        if not by_dataset:
            print(f"{tenant_id:<12} {'(none)':<16} {0:>6}")
            continue
        for dataset_type, dataset_fields in sorted(by_dataset.items()):
            wired = "yes" if dataset_type in WIRED_IN else "NO -- add a builder in dynamic_context.py"
            print(f"{tenant_id:<12} {dataset_type:<16} {len(dataset_fields):>6}  {wired}")
    print()


def main():
    tenants = _distinct_tenants()

    lines = [
        "# Dynamic Fields Report",
        "",
        "Auto-generated by `scripts/generate_dynamic_fields_report.py`. "
        "Lists every tenant-specific column currently tracked in "
        "`dynamic_field_registry` — i.e. columns a tenant's raw file had "
        "that don't map to any field in the fixed core schema "
        "(see `docs/er_diagram.md`).",
        "",
        "These values live in each row's `extra_attributes` JSON column; "
        "this registry is metadata *about* that JSON, used to decide (a) "
        "whether an agent should see the field at all (`relevance`), and "
        "(b) how to describe it in plain language when it does.",
        "",
    ]

    if not tenants:
        lines.append("_No dynamic fields discovered yet — run "
                      "`scripts/run_tenant_ingestion.py` first._")
    else:
        for tenant_id in tenants:
            lines.append(f"## {tenant_id}")
            lines.append("")
            # include ignored fields here too, since this is a diagnostic report
            fields = db.get_dynamic_fields(tenant_id, exclude_ignored=False)
            by_dataset = {}
            for f in fields:
                by_dataset.setdefault(f["dataset_type"], []).append(f)

            for dataset_type, dataset_fields in sorted(by_dataset.items()):
                lines.append(f"**{dataset_type}**")
                lines.append("")
                lines.append("| field_name | source_column | relevance | inferred_type | description | confidence |")
                lines.append("|---|---|---|---|---|---|")
                for f in dataset_fields:
                    lines.append(
                        f"| `{f['field_name']}` | `{f['source_column']}` | {f['relevance']} "
                        f"| {f['inferred_type']} | {f['description']} | {f['confidence']:.2f} |"
                    )
                lines.append("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {os.path.abspath(OUT_PATH)}")
    print(f"Tenants with discovered fields: {tenants or '(none)'}")
    _print_console_summary(tenants)


if __name__ == "__main__":
    main()
